name: release-please
on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: ${{ github.event.repository.name }}
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: ${{ matrix.node-version }}
          # Use the Github Package registry
          registry-url: https://npm.pkg.github.com/
          scope: '@aave'
      # Generate a random SSH key at runtime due ethereumjs-abi https://github.com/ethereumjs/ethereumjs-abi/issues/67#issuecomment-681944008
      - name: Generate SSH key for Github authentication
        run: ssh-keygen -q -t rsa -N '' <<< $'\ny' >/dev/null 2>&1
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run ci:test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
